export const carData = [
  {
    category: "Popular Car",
    items: [
      {
        name: "Koenigsegg",
        type: "Sport",
        fuelCapacity: "90L",
        transmission: "Manual",
        passengerCapacity: "2People",
        pricePerDay: "$99.00/",
        rentNow: "Rent Now",
      },
      {
        name: "Nissan GT - R",
        type: "Sport",
        fuelCapacity: "80L",
        transmission: "Manual",
        passengerCapacity: "2People",
        pricePerDay: "$80.00/",
        rentNow: "Rent Now",
      },
      {
        name: "Rolls - Royce",
        type: "Sedan",
        fuelCapacity: "70L",
        transmission: "Manual",
        passengerCapacity: "4People",
        pricePerDay: "$96.00/",
        rentNow: "Rent Now",
      },
      {
        name: "Rolls - Royce",
        type: "Sedan",
        fuelCapacity: "70L",
        transmission: "Manual",
        passengerCapacity: "4People",
        pricePerDay: "$96.00/",
        rentNow: "Rent Now",
      },
    ],
  },
  {
    category: "Recomendation Car",
    items: [
      {
        name: "All New Rush",
        type: "SUV",
        fuelCapacity: "70L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$72.00/",
        rentNow: "Rent Now",
      },
      {
        name: "CR  - V",
        type: "SUV",
        fuelCapacity: "80L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$80.00/",
        rentNow: "Rent Now",
      },
      {
        name: "All New Terios",
        type: "SUV",
        fuelCapacity: "90L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$74.00/",
        rentNow: "Rent Now",
      },
      {
        name: "MG ZX Exclusice",
        type: "Hatchback",
        fuelCapacity: "70L",
        transmission: "Manual",
        passengerCapacity: "4People",
        pricePerDay: "$76.00/",
        rentNow: "Rent Now",
      },
      {
        name: "New MG ZS",
        type: "SUV",
        fuelCapacity: "80L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$80.00/",
        rentNow: "Rent Now",
      },
      {
        name: "MG ZX Excite",
        type: "Hatchback",
        fuelCapacity: "90L",
        transmission: "Manual",
        passengerCapacity: "4People",
        pricePerDay: "$74.00/",
        rentNow: "Rent Now",
      },
      {
        name: "CR  - V",
        type: "SUV",
        fuelCapacity: "80L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$80.00/",
        rentNow: "Rent Now",
      },
      {
        name: "All New Terios",
        type: "SUV",
        fuelCapacity: "90L",
        transmission: "Manual",
        passengerCapacity: "6People",
        pricePerDay: "$74.00/",
        rentNow: "Rent Now",
      },
    ],
  },
];
